# GUI file generated by GUI Pie, developed by Jabberwock
# https://apps.microsoft.com/store/detail/gui-pie/9P5TH15LZSL7


import os
import sys
import subprocess
import math
from tkinter import *
from tkinter import ttk
import tkinter.font
try:
  from PIL import ImageTk, Image, ImageOps
except:
  print('Installing PIL.')
  subprocess.check_call(['pip', 'install', 'pillow'])
  print('Done.')
  from PIL import ImageTk, Image, ImageOps

if __name__ == "__main__":
  test2 = Tk()
else:
  test2 = Tk()
test2.title('test2')
dpi = 96
test2.geometry('400x440')
test2.grid_propagate(False)
for x in range(10):
  Grid.columnconfigure(test2, x, weight=1, uniform='row')
  Label(test2, width = 1, bg = '#FFFFFF').grid(row = 0, column = x, sticky = N+S+E+W)
for y in range(11):
  Grid.rowconfigure(test2, y, weight=1, uniform='row')
  Label(test2, width = 1, bg = '#FFFFFF').grid(row = y, column = 0, sticky = N+S+E+W)
test2.configure(background='#FFFFFF')

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~WIDGETS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

test2.Image1_test1Original = Image.open(r'C:/Users/Bmadr/Downloads/apps.44156.14632704454246972.9d2634b3-3b7d-4005-8787-982a7c3c46c0.png')
test2.Image1_test1Image = ImageOps.exif_transpose(test2.Image1_test1Original)
test2.Image1_test1Image = ImageTk.PhotoImage(test2.Image1_test1Image.resize((math.ceil(320 * dpi / 96), math.ceil(240 * dpi / 96)), Image.Resampling.LANCZOS))
test2.Label1_test = Label(test2, text = "nothing", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#FF0000')
test2.Label1_test.grid(row = 0, column = 0, columnspan = 10, rowspan = 1, sticky = N+S+E+W)
test2.Label1_test1 = Label(test2, text = "how this works", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#0000FF')
test2.Label1_test1.grid(row = 0, column = 0, columnspan = 10, rowspan = 1, sticky = N+S+E+W)
test2.Label2_test1 = Label(test2, text = "this was made with GUI pie it is a gui python maker you can find it at", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#C6C6C6')
test2.Label2_test1.grid(row = 1, column = 0, columnspan = 10, rowspan = 2, sticky = N+S+E+W)
test2.Label6_test1 = Label(test2, text = "", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#000000')
test2.Label6_test1.grid(row = 4, column = 9, columnspan = 1, rowspan = 6, sticky = N+S+E+W)
test2.Label3_test1 = Label(test2, text = "", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', bg = '#000000')
test2.Label3_test1.grid(row = 4, column = 0, columnspan = 1, rowspan = 6, sticky = N+S+E+W)
test2.Entry1_add = Entry(test2, width = 1, bg = '#0000FF', font = ('Arial', 16), justify = 'center')
test2.Entry1_add.grid(row = 0, column = 0, columnspan = 10, rowspan = 2, sticky = N+S+E+W)
test2.Entry1_add.insert(0, "not working")
test2.Entry1_test = Entry(test2, width = 1, bg = '#FFFFFF', font = ('Arial', 16), justify = 'center')
test2.Entry1_test.grid(row = 1, column = 0, columnspan = 10, rowspan = 2, sticky = N+S+E+W)
test2.Entry1_test.insert(0, "text here")
def defocus(event):
  event.widget.master.focus_set()
test2.down_test = ttk.Combobox(test2, values = ['1','2','reset','how this works',], width = 1, state = 'readonly')
test2.down_test.grid(row = 6, column = 0, columnspan = 10, rowspan = 2, sticky = N+S+E+W)
test2.down_test.bind('<FocusIn>', defocus)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~BUTTONS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def runadd(argument):
  if not(__name__ == '__main__'):
    from main import add
    try:
      add(argument)
    except TypeError:
      add()
def runreset(argument):
  if not(__name__ == '__main__'):
    from main import reset
    try:
      reset(argument)
    except TypeError:
      reset()
def runreadtext(argument):
  if not(__name__ == '__main__'):
    from main import readtext
    try:
      readtext(argument)
    except TypeError:
      readtext()
def runread(argument):
  if not(__name__ == '__main__'):
    from main import read
    try:
      read(argument)
    except TypeError:
      read()
def runwebload(argument):
  if not(__name__ == '__main__'):
    from main import webload
    try:
      webload(argument)
    except TypeError:
      webload()
def runback(argument):
  if not(__name__ == '__main__'):
    from main import back
    try:
      back(argument)
    except TypeError:
      back()
def runmore(argument):
  if not(__name__ == '__main__'):
    from main import more
    try:
      more(argument)
    except TypeError:
      more()
def runmore2(argument):
  if not(__name__ == '__main__'):
    from main import more2
    try:
      more2(argument)
    except TypeError:
      more2()
test2.Button1_add = Button(test2, text = "add", font = ('Arial', 16), width = 1, height = 1, fg = '#FFFFFF', command = lambda: runadd('Button1_add'), bg = '#000000')
test2.Button1_add.grid(row = 2, column = 0, columnspan = 5, rowspan = 7, sticky = N+S+E+W)
test2.Button2_add = Button(test2, text = "add", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runadd('Button2_add'), bg = '#C6C6C6')
test2.Button2_add.grid(row = 2, column = 5, columnspan = 5, rowspan = 7, sticky = N+S+E+W)
test2.reset_add = Button(test2, text = "back", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runreset('reset_add'), bg = '#FF0000')
test2.reset_add.grid(row = 9, column = 0, columnspan = 10, rowspan = 2, sticky = N+S+E+W)
test2.read_text_test = Button(test2, text = "read text", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runreadtext('read_text_test'), bg = '#C6C6C6')
test2.read_text_test.grid(row = 3, column = 0, columnspan = 10, rowspan = 3, sticky = N+S+E+W)
test2.read1_test = Button(test2, text = "read", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runread('read1_test'), bg = '#C6C6C6')
test2.read1_test.grid(row = 8, column = 0, columnspan = 10, rowspan = 3, sticky = N+S+E+W)
test2.Button1_test1 = Button(test2, text = "here", font = ('Arial', 16), width = 1, height = 1, fg = '#FFFFFF', command = lambda: runwebload('Button1_test1'), bg = '#000000')
test2.Button1_test1.grid(row = 3, column = 0, columnspan = 10, rowspan = 1, sticky = N+S+E+W)
test2.Button2_test1 = Button(test2, text = "back", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runback('Button2_test1'), bg = '#C6C6C6')
test2.Button2_test1.grid(row = 10, column = 0, columnspan = 5, rowspan = 1, sticky = N+S+E+W)
test2.Button3_test1 = Button(test2, text = "more", font = ('Arial', 16), width = 1, height = 1, fg = '#000000', command = lambda: runmore('Button3_test1'), bg = '#C6C6C6')
test2.Button3_test1.grid(row = 10, column = 5, columnspan = 5, rowspan = 1, sticky = N+S+E+W)
test2.Image1_test1 = Button(test2, image = test2.Image1_test1Image, width = 1, height = 1, bg = '#FFFFFF', activebackground = '#FFFFFF', command = lambda: runmore2('Image1_test1'), highlightthickness=0, relief='flat')
test2.Image1_test1.grid(row = 4, column = 1, columnspan = 8, rowspan = 6, sticky = N+S+E+W)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~HELPER FUNCTIONS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

def initModules():
  raise Exception('This main file is outdated. Script main.py must be updated to reflect the changes in GUI Pie v3.')
def init():
  from main import add
  from main import reset
  from main import readtext
  from main import read
  from main import webload
  from main import back
  from main import more
  from main import more2
test2.initModules = initModules
def hide():
  test2.withdraw()
def show():
  test2.deiconify()
def hideAllWidgets():
    test2.Label1_test.grid_remove()
    test2.Label1_test1.grid_remove()
    test2.Label2_test1.grid_remove()
    test2.Label6_test1.grid_remove()
    test2.Label3_test1.grid_remove()
    test2.Entry1_add.grid_remove()
    test2.Entry1_test.grid_remove()
    test2.Button1_add.grid_remove()
    test2.Button2_add.grid_remove()
    test2.reset_add.grid_remove()
    test2.read_text_test.grid_remove()
    test2.read1_test.grid_remove()
    test2.Button1_test1.grid_remove()
    test2.Button2_test1.grid_remove()
    test2.Button3_test1.grid_remove()
    test2.down_test.grid_remove()
    test2.Image1_test1.grid_remove()
test2.hideAllWidgets = hideAllWidgets
def showAllWidgets():
    test2.Label1_test.grid()
    test2.Label1_test1.grid()
    test2.Label2_test1.grid()
    test2.Label6_test1.grid()
    test2.Label3_test1.grid()
    test2.Entry1_add.grid()
    test2.Entry1_test.grid()
    test2.Button1_add.grid()
    test2.Button2_add.grid()
    test2.reset_add.grid()
    test2.read_text_test.grid()
    test2.read1_test.grid()
    test2.Button1_test1.grid()
    test2.Button2_test1.grid()
    test2.Button3_test1.grid()
    test2.down_test.grid()
    test2.Image1_test1.grid()
test2.showAllWidgets = showAllWidgets
def run():
  global dimensions
  dimensions = [0,0]
  if __name__ != "__main__":
    init()
  resizeEvent(None)
  test2.mainloop()
test2.run = run
test2.hide = hide
test2.show = show
def hideaddWidgets():
  test2.Entry1_add.grid_remove()
  test2.Button1_add.grid_remove()
  test2.Button2_add.grid_remove()
  test2.reset_add.grid_remove()
def showaddWidgets():
  global dimensions
  dimensions = [0,0]
  test2.Entry1_add.grid()
  test2.Button1_add.grid()
  test2.Button2_add.grid()
  test2.reset_add.grid()
  resizeEvent(None)
test2.showaddWidgets = showaddWidgets
test2.hideaddWidgets = hideaddWidgets

def hidetestWidgets():
  test2.Label1_test.grid_remove()
  test2.Entry1_test.grid_remove()
  test2.read_text_test.grid_remove()
  test2.read1_test.grid_remove()
  test2.down_test.grid_remove()
def showtestWidgets():
  global dimensions
  dimensions = [0,0]
  test2.Label1_test.grid()
  test2.Entry1_test.grid()
  test2.read_text_test.grid()
  test2.read1_test.grid()
  test2.down_test.grid()
  resizeEvent(None)
test2.showtestWidgets = showtestWidgets
test2.hidetestWidgets = hidetestWidgets

def hidetest1Widgets():
  test2.Label1_test1.grid_remove()
  test2.Label2_test1.grid_remove()
  test2.Label6_test1.grid_remove()
  test2.Label3_test1.grid_remove()
  test2.Button1_test1.grid_remove()
  test2.Button2_test1.grid_remove()
  test2.Button3_test1.grid_remove()
  test2.Image1_test1.grid_remove()
def showtest1Widgets():
  global dimensions
  dimensions = [0,0]
  test2.Label1_test1.grid()
  test2.Label2_test1.grid()
  test2.Label6_test1.grid()
  test2.Label3_test1.grid()
  test2.Button1_test1.grid()
  test2.Button2_test1.grid()
  test2.Button3_test1.grid()
  test2.Image1_test1.grid()
  resizeEvent(None)
test2.showtest1Widgets = showtest1Widgets
test2.hidetest1Widgets = hidetest1Widgets

def showDefaultPage():
  showaddWidgets()
dimensions = [test2.winfo_width(), test2.winfo_height()]
def resize():
  global test2, dimensions
  if test2.winfo_width() != dimensions[0] or test2.winfo_height() != dimensions[1]:
    test2.Label1_test.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.Label1_test1.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.Label2_test1.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.Label6_test1.config(wraplength = math.ceil(test2.winfo_width() * 1 / 10) + 2)
    test2.Label3_test1.config(wraplength = math.ceil(test2.winfo_width() * 1 / 10) + 2)
    test2.Button1_add.config(wraplength = math.ceil(test2.winfo_width() * 5 / 10) + 2)
    test2.Button2_add.config(wraplength = math.ceil(test2.winfo_width() * 5 / 10) + 2)
    test2.reset_add.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.read_text_test.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.read1_test.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.Button1_test1.config(wraplength = math.ceil(test2.winfo_width() * 10 / 10) + 2)
    test2.Button2_test1.config(wraplength = math.ceil(test2.winfo_width() * 5 / 10) + 2)
    test2.Button3_test1.config(wraplength = math.ceil(test2.winfo_width() * 5 / 10) + 2)
    test2.Image1_test1Original = Image.open(r'C:/Users/Bmadr/Downloads/apps.44156.14632704454246972.9d2634b3-3b7d-4005-8787-982a7c3c46c0.png')
    test2.Image1_test1Image = ImageOps.exif_transpose(test2.Image1_test1Original)
    test2.Image1_test1Image = ImageTk.PhotoImage(test2.Image1_test1Image.resize((math.ceil(test2.winfo_width() * 8 / 10), math.ceil(test2.winfo_height() * 6 / 11)), Image.Resampling.LANCZOS))
    test2.Image1_test1.config(image = test2.Image1_test1Image)
    dimensions = [test2.winfo_width(), test2.winfo_height()]

eventID = None
test2.resizeDelay = 100
def resizeEvent(event):
  global eventID
  if eventID:
    test2.after_cancel(eventID)
  eventID = test2.after(test2.resizeDelay, resize)
test2.bind('<Configure>', resizeEvent)
hideAllWidgets()
if __name__ == "__main__":
  showDefaultPage()
  test2.run()
